name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: start containers
      run: docker compose -f "compose.yaml" up -d --build

    - name: Restore dependencies
      run: dotnet restore TestProject/TestProject.csproj

    - name: Build project
      run: dotnet build TestProject/TestProject.csproj --configuration Release

    - name: Run tests
      run: dotnet test TestProject/TestProject.csproj --configuration Release      
      
